// lib/filingcontrol/calendar/ics.ts
// Pure, deterministic ICS calendar generator for FilingControl deadlines.
// RFC 5545 compliant. No side effects.

export type CalendarEntity = {
  id: string
  company_name: string
}

export type CalendarDeadline = {
  form: string
  dueDate: string // ISO date YYYY-MM-DD
  basis?: string
}

export type CalendarInput = {
  entities: Array<{
    entity: CalendarEntity
    deadlines: CalendarDeadline[]
  }>
  now: Date
  dtstamp?: string // override for deterministic tests
}

/**
 * Format a Date as ICS DTSTAMP (UTC): YYYYMMDDTHHMMSSZ
 */
function formatDTStamp(d: Date): string {
  return d.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '')
}

/**
 * Format a YYYY-MM-DD date as ICS VALUE=DATE: YYYYMMDD
 */
function formatDateValue(iso: string): string {
  return iso.replace(/-/g, '')
}

/**
 * Build a deterministic UID for a VEVENT.
 */
function buildUID(entityId: string, form: string, dueDate: string): string {
  return `fc-${entityId}-${form}-${dueDate}`
}

/**
 * Escape text for ICS content lines (RFC 5545 §3.3.11).
 */
function escapeText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
}

/**
 * Generate an RFC 5545 ICS calendar string from entity deadlines.
 *
 * - Events sorted ascending by dueDate.
 * - Past deadlines older than 30 days from `now` are excluded.
 * - Deterministic: same inputs => same output (except DTSTAMP if not overridden).
 */
export function generateICS(input: CalendarInput): string {
  const { entities, now, dtstamp } = input
  const stamp = dtstamp ?? formatDTStamp(now)

  // Cutoff: exclude deadlines older than 30 days
  const cutoff = new Date(now)
  cutoff.setDate(cutoff.getDate() - 30)
  const cutoffStr = cutoff.toISOString().split('T')[0]

  // Collect all events
  const events: Array<{
    uid: string
    dtstart: string
    summary: string
    description: string
    dueDate: string
  }> = []

  for (const { entity, deadlines } of entities) {
    for (const dl of deadlines) {
      // Filter out old past deadlines
      if (dl.dueDate < cutoffStr) continue

      const daysRemaining = Math.floor(
        (new Date(dl.dueDate).getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
      )

      const descParts = [
        `Entity: ${entity.company_name}`,
        `Due: ${dl.dueDate}`,
      ]
      if (daysRemaining >= 0) {
        descParts.push(`Days remaining: ${daysRemaining}`)
      }
      descParts.push('Generated by FilingControl (EchoLegal)')

      events.push({
        uid: buildUID(entity.id, dl.form, dl.dueDate),
        dtstart: formatDateValue(dl.dueDate),
        summary: `${dl.form} \u2013 Filing Deadline`,
        description: descParts.join('\\n'),
        dueDate: dl.dueDate,
      })
    }
  }

  // Sort ascending by dueDate, then by uid for stability
  events.sort((a, b) => {
    if (a.dueDate !== b.dueDate) return a.dueDate < b.dueDate ? -1 : 1
    return a.uid < b.uid ? -1 : a.uid > b.uid ? 1 : 0
  })

  // Build ICS
  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//EchoLegal//FilingControl//EN',
    'CALSCALE:GREGORIAN',
  ]

  for (const evt of events) {
    lines.push(
      'BEGIN:VEVENT',
      `UID:${escapeText(evt.uid)}`,
      `DTSTAMP:${stamp}`,
      `DTSTART;VALUE=DATE:${evt.dtstart}`,
      `SUMMARY:${escapeText(evt.summary)}`,
      `DESCRIPTION:${escapeText(evt.description)}`,
      'END:VEVENT'
    )
  }

  lines.push('END:VCALENDAR')

  return lines.join('\r\n')
}
